# Generated by Django 5.1.4 on 2025-01-09 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boostlab_tasks', '0003_alter_task_assinged_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='assinged_by',
            new_name='manager',
        ),
    ]
