# Generated by Django 5.1.4 on 2025-01-09 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boostlab_tasks', '0004_rename_assinged_by_task_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='manager',
        ),
    ]
