# Generated by Django 5.1.4 on 2025-01-09 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boostlab_employees', '0004_department_employee_department_manager'),
        ('boostlab_tasks', '0006_task_assinged_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assinged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to='boostlab_employees.manager'),
        ),
    ]
