# Generated by Django 5.1.4 on 2024-12-29 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boostlab_posts', '0002_tag_alter_post_options_post_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='tag',
            name='order',
            field=models.IntegerField(null=True),
        ),
    ]
