# Generated by Django 5.1.4 on 2024-12-29 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boostlab_posts', '0003_alter_tag_options_tag_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='icons/'),
        ),
    ]
