# Generated by Django 5.1.4 on 2024-12-29 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boostlab_employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
