# Generated by Django 5.1.4 on 2024-12-31 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boostlab_employees', '0002_alter_employee_image_alter_employee_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics'),
        ),
    ]
