# Generated by Django 5.1.4 on 2025-01-09 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boostlab_employees', '0004_department_employee_department_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager', to='boostlab_employees.employee'),
        ),
    ]
