# Generated by Django 5.1.4 on 2025-01-09 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boostlab_employees', '0005_alter_manager_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manager',
            old_name='user',
            new_name='employee',
        ),
    ]
