# Generated by Django 5.1.4 on 2025-01-10 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boostlab_employees', '0007_alter_employee_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manager', to='boostlab_employees.employee'),
        ),
    ]
